---
- name: Base configuration
  hosts: all
  become: true
  roles:
    - bootstrap
    - ssh
    - private_net
    - wireguard

- name: Host firewall
  hosts: core,edge
  become: true
  serial: 1
  roles:
    - nftables
