---
- name: Base configuration
  hosts: all
  become: true
  roles:
    - bootstrap
    - ssh
    - private_net
    - wireguard

- name: Host firewall
  hosts: core,edge
  become: true
  serial: 1
  roles:
    - nftables

- name: Container runtime
  hosts: all
  become: true
  roles:
    - docker

- name: Database (core only)
  hosts: core
  become: true
  roles:
    - mariadb
