---
backup_s3_bucket: "{{ vault_backup_s3_bucket }}"
backup_s3_namespace: "{{ vault_backup_s3_namespace }}"
backup_s3_region: "{{ vault_backup_s3_region }}"
restic_password: "{{ vault_restic_password }}"
oci_s3_access_key: "{{ vault_oci_s3_access_key }}"
oci_s3_secret_key: "{{ vault_oci_s3_secret_key }}"
