---
- name: Reload nginx
  ansible.builtin.command: docker exec nginx nginx -s reload  # noqa: command-instead-of-module
  changed_when: true

- name: Restart certbot renewal timer
  ansible.builtin.systemd:
    name: certbot-renew.timer
    state: restarted
    daemon_reload: true
