---
mariadb_root_password: "{{ vault_mariadb_root_password }}"
mariadb_wp_password: "{{ vault_mariadb_wp_password }}"
mariadb_bind_ip: 10.66.0.2
nftables_wg_input_tcp: [9100]
nftables_wg_forward_tcp: [3306]
